CREATE DEFINER=`105408525`@`192.168.56.1` PROCEDURE `sp_BookTicket`(
	in in_userID int,
    in in_email varchar(200),
    in in_train_id int, 
    in in_dep_station int,
    in in_arr_station int, 
    in in_train_date datetime, -- detail time of the train user selected
    out login_message varchar(250),
    out book_message varchar(250),
    out num_row int(10)
    
)
BEGIN
	declare sel_seat_id varchar(100) ;
    declare sel_dep_time varchar(100) ;
    declare sel_price double ;
    
    -- User has to login to book the ticket
    if exists ( select * from User where user_id = in_userID and email =  in_email) then 
		set login_message = (select " User Login succesfully, please start booking tickets" ) ;

		call db_105408525.QueryTicket_forCall(in_train_date, 
										      in_dep_station, 
										      in_arr_station) ;
	
    -- user pick the seat and train from the table generated by the `QueryTicket_forCall` procedure
 
		if exists (select * from ticketQueryWithSeats) then
        
			set sel_seat_id = (	select seat_id from ticketQueryWithSeats 
								where train_id = in_train_id limit 1 ) ;
			set sel_dep_time = (select departure_time from ticketQueryWithSeats 
								where train_id = in_train_id and seat_id = sel_seat_id limit 1 ) ;
			set sel_price = (select price from ticketQueryWithSeats 
							 where train_id = in_train_id and seat_id = sel_seat_id limit 1 ) ;
        
			insert into Ticket 
				values(null, in_userID, sel_dep_time, in_train_id, in_dep_station, in_arr_station, sel_seat_id, sel_price, current_timestamp(), null) ;
        
			drop table if exists `result_set` ;    
		
			create temporary table result_set as
			select * from Ticket 
			where user_id = in_userID and train_id = in_train_id and train_date = sel_dep_time and seat_id = sel_seat_id;
        
			select ticket_id, user_id, train_id, departure_station, arrival_station, seat_id, book_time, train_date
			from result_set ;
        
			set book_message = (select "Ticket Booked Succesfully") ;
            set num_row = (select count(*) from result_set) ;
		
        else 
			set book_message = (select "No Train is available" ) ;
            set num_row = (select 0) ;
        
		end if ;
	else 
		set login_message = (select "User not found") ;
        set book_message = (select "Please login user account for booking tickets" );
        set num_row = (select 0) ;
	
    end if ;
                                     
	
END